"""Static manifest of every example tune across the bundled d64 images.

Generated by walking the directory chains of both pristine images. The
on-disk names start with '.' and exceed defMON's 15-typed-char save
limit, so typed-name loading can't round-trip them — callers must use
``Defmon.disk_load_by_index`` against the precomputed ``dir_index``.

`dir_index` is the number of CRSRUD presses from the moment the disk
menu's directory listing first appears (cursor at row 0). It is
**not** an index into the TUNES tuple; it indexes defMON's on-screen
directory rows, which include decorative DEL header rows ("------",
author bylines like "ILKKE") as cursor stops. Verified empirically by
``tools/dir_indices.py``.

Decorative DEL entries are intentionally absent from TUNES (they aren't
real files), but their cursor positions are accounted for in dir_index.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class TuneEntry:
    image: str  # source d64 filename (basename)
    name: str  # on-disk PETSCII name as printed in the dir
    blocks: int  # 254-byte block count from the dir entry
    track: int  # first-block track
    sector: int  # first-block sector
    author: str  # editorial grouping from the on-disk header rows
    dir_index: int  # CRSRUD presses from disk-menu open to land on this row


TUNES: tuple[TuneEntry, ...] = (
    TuneEntry("defmon-withtunes.d64", ".GLOW WORM", 18, 4, 11, "ILKKE", dir_index=4),
    TuneEntry("defmon-withtunes.d64", ".HIVE MACHINES", 18, 5, 2, "ILKKE", dir_index=5),
    TuneEntry("defmon-withtunes.d64", ".VACUOLE", 43, 6, 16, "ILKKE", dir_index=6),
    TuneEntry("defmon-withtunes.d64", ".RADIO ROBON95", 21, 8, 4, "ILKKE", dir_index=7),
    TuneEntry("defmon-withtunes.d64", ".F7SUS4-NGC1277", 16, 9, 4, "F7SUS4", dir_index=11),
    TuneEntry("defmon-withtunes.d64", ".MONDAYNIGHT2017", 35, 10, 20, "GOTO80", dir_index=15),
    TuneEntry("defmon-withtunes.d64", ".DANSA IN", 29, 11, 15, "GOTO80", dir_index=16),
    TuneEntry("defmon-withtunes.d64", ".MATSAM0T", 30, 13, 8, "GOTO80", dir_index=17),
    TuneEntry("defmon-withtunes.d64", ".AUTOMATAS2017", 69, 14, 11, "GOTO80", dir_index=18),
)


def tunes_for_image(image: str) -> tuple[TuneEntry, ...]:
    return tuple(t for t in TUNES if t.image == image)
